Repository openwrt/luci, pull requests merged in 2019-12, with the labels that each got.

#3348 luci-app-yggdrasil: Add application for Yggdrasil
  applications/luci-app-yggdrasil/Makefile
  applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/keys.js
  applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/peers.js
  applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/session_firewall.js
  applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/settings.js
  applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/status.js
  applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/tunnel_routing.js
  applications/luci-app-yggdrasil/luasrc/controller/yggdrasil.lua
  applications/luci-app-yggdrasil/root/usr/share/rpcd/acl.d/luci-app-yggdrasil.json
Labels: feature

#3376 add luci support for omcproxy
  applications/luci-app-omcproxy/Makefile
  applications/luci-app-omcproxy/htdocs/luci-static/resources/view/omcproxy.js
  applications/luci-app-omcproxy/luasrc/controller/omcproxy.lua
  applications/luci-app-omcproxy/po/templates/omcproxy.pot
  applications/luci-app-omcproxy/po/zh-cn/omcproxy.po
Labels: feature

#3373 luci-app-aria2: fix typos
  applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua
  applications/luci-app-aria2/po/bg/aria2.po
  applications/luci-app-aria2/po/ca/aria2.po
  applications/luci-app-aria2/po/cs/aria2.po
  applications/luci-app-aria2/po/de/aria2.po
  applications/luci-app-aria2/po/el/aria2.po
  applications/luci-app-aria2/po/en/aria2.po
  applications/luci-app-aria2/po/es/aria2.po
  applications/luci-app-aria2/po/fr/aria2.po
  applications/luci-app-aria2/po/he/aria2.po
  applications/luci-app-aria2/po/hi/aria2.po
  applications/luci-app-aria2/po/hu/aria2.po
  applications/luci-app-aria2/po/it/aria2.po
  applications/luci-app-aria2/po/ja/aria2.po
  applications/luci-app-aria2/po/ko/aria2.po
  applications/luci-app-aria2/po/ms/aria2.po
  applications/luci-app-aria2/po/nb_NO/aria2.po
  applications/luci-app-aria2/po/pl/aria2.po
  applications/luci-app-aria2/po/pt-br/aria2.po
  applications/luci-app-aria2/po/pt/aria2.po
  applications/luci-app-aria2/po/ro/aria2.po
  applications/luci-app-aria2/po/ru/aria2.po
  applications/luci-app-aria2/po/sk/aria2.po
  applications/luci-app-aria2/po/sv/aria2.po
  applications/luci-app-aria2/po/tr/aria2.po
  applications/luci-app-aria2/po/uk/aria2.po
  applications/luci-app-aria2/po/vi/aria2.po
  applications/luci-app-aria2/po/zh-cn/aria2.po
  applications/luci-app-aria2/po/zh-tw/aria2.po
Labels: WIP, fix

#3425 luci-app-fwknopd: fix typos
  applications/luci-app-fwknopd/luasrc/model/cbi/fwknopd.lua
  applications/luci-app-fwknopd/po/bg/fwknopd.po
  applications/luci-app-fwknopd/po/ca/fwknopd.po
  applications/luci-app-fwknopd/po/cs/fwknopd.po
  applications/luci-app-fwknopd/po/de/fwknopd.po
  applications/luci-app-fwknopd/po/el/fwknopd.po
  applications/luci-app-fwknopd/po/en/fwknopd.po
  applications/luci-app-fwknopd/po/es/fwknopd.po
  applications/luci-app-fwknopd/po/fr/fwknopd.po
  applications/luci-app-fwknopd/po/he/fwknopd.po
  applications/luci-app-fwknopd/po/hi/fwknopd.po
  applications/luci-app-fwknopd/po/hu/fwknopd.po
  applications/luci-app-fwknopd/po/it/fwknopd.po
  applications/luci-app-fwknopd/po/ja/fwknopd.po
  applications/luci-app-fwknopd/po/ko/fwknopd.po
  applications/luci-app-fwknopd/po/mr/fwknopd.po
  applications/luci-app-fwknopd/po/ms/fwknopd.po
  applications/luci-app-fwknopd/po/nb_NO/fwknopd.po
  applications/luci-app-fwknopd/po/pl/fwknopd.po
  applications/luci-app-fwknopd/po/pt-br/fwknopd.po
  applications/luci-app-fwknopd/po/pt/fwknopd.po
  applications/luci-app-fwknopd/po/ro/fwknopd.po
  applications/luci-app-fwknopd/po/ru/fwknopd.po
  applications/luci-app-fwknopd/po/sk/fwknopd.po
  applications/luci-app-fwknopd/po/sv/fwknopd.po
  applications/luci-app-fwknopd/po/tr/fwknopd.po
  applications/luci-app-fwknopd/po/uk/fwknopd.po
  applications/luci-app-fwknopd/po/vi/fwknopd.po
  applications/luci-app-fwknopd/po/zh-cn/fwknopd.po
  applications/luci-app-fwknopd/po/zh-tw/fwknopd.po
  applications/luci-app-fwknopd/root/etc/uci-defaults/40_luci-fwknopd
  docs/api/modules/nixio.bin.html
  libs/luci-lib-nixio/docsrc/nixio.bin.lua
Labels: translation

#3352 luci-base: use luasrcdiet from separate package
  luci.mk
  modules/luci-base/Makefile
Labels: fix

#1951 luci-base: network.lua: bridge information request functions fixes
  modules/luci-compat/luasrc/model/network.lua
Labels: fix

#3400 luci.mk: move indexcache delete into postinst
  luci.mk
Labels: feature
