Repository openwrt/luci, pull requests merged in 2019-10, with the labels that each got.

#3064 luci-app-commands: fix escaping of additional shell chars
  applications/luci-app-commands/luasrc/controller/commands.lua
Labels: fix

#3128 luci-base: zh_CN: update Simplified Chinese translation
  modules/luci-base/po/zh-cn/base.po
Labels: translation

#3142 luci-app-banip: sync with banIP 0.3.0
  applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua
  applications/luci-app-banip/luasrc/view/banip/runtime.htm
Labels: depends on pr, feature

#3134 luci-app-https_dns_proxy: bugfix: proper formatting of dhcp server entries
  applications/luci-app-https_dns_proxy/Makefile
  applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
Labels: fix

#3133 [19.07] luci-app-https_dns_proxy: bugfix: proper formatting of dhcp server entries
  applications/luci-app-https_dns_proxy/Makefile
  applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
Labels: fix, release/19.07

#3157 luci-base: fix typo in german translation
  modules/luci-base/po/de/base.po
Labels: translation

#3159 luci-app-statistics: fix german translation
  applications/luci-app-statistics/po/de/statistics.po
Labels: translation

#3160 luci-app-mosquitto: drop tls1.0, add tls1.3
  applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua
Labels: fix

#3158 luci-app-banip: sync with update 0.3.1
  applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua
Labels: depends on pr, feature

#3151 luci-app-https_dns_proxy: bugfix: subnet address datatype, add DNS.SB provider
  applications/luci-app-https_dns_proxy/Makefile
  applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
Labels: fix

#3153 [19.07] luci-app-https_dns_proxy: bugfix: subnet address datatype, add DNS.SB provider
  applications/luci-app-https_dns_proxy/Makefile
  applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
Labels: fix, release/19.07

#3058 luci-app-dcwapd: Add Dual Channel Wi-Fi AP Daemon Management LuCI pages
  applications/luci-app-dcwapd/Makefile
  applications/luci-app-dcwapd/luasrc/controller/dcwapd.lua
  applications/luci-app-dcwapd/luasrc/model/cbi/dcwapd/dcwapd.lua
  applications/luci-app-dcwapd/root/etc/uci-defaults/60_luci-dcwapd
Labels: feature

#3167 luci-theme-bootstrap: replace the old favicon
  applications/luci-app-noddos/htdocs/cgi-bin/clientdetails
  themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/favicon.ico
  themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/favicon.png
  themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm
Labels: feature

#3171 [18.06] luci-app-simple-adblock: bugfix: fix invalid <br> entries
  applications/luci-app-simple-adblock/Makefile
  applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua
  applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
Labels: fix, release/18.06

#3179 luci-app-openvpn: add missing proto param for ipv6
  applications/luci-app-openvpn/luasrc/model/cbi/openvpn-basic.lua
Labels: fix

#3175 luci-proto-modemmanager: add luci-proto-modemmanager
  protocols/luci-proto-modemmanager/Makefile
  protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
  protocols/luci-proto-modemmanager/luasrc/model/network/proto_modemmanager.lua
Labels: feature

#3184 luci-app-firewall: update Simplified Chinese translation
  applications/luci-app-firewall/po/zh-cn/firewall.po
Labels: translation

#3185 luci-app-simple-adblock: update Simplefied Chinese translation
  applications/luci-app-simple-adblock/po/zh-cn/simple-adblock.po
Labels: translation

#3188 luci-app-advanced-reboot: update Simplified Chinese translation
  applications/luci-app-advanced-reboot/po/zh-cn/advanced-reboot.po
Labels: translation

#3189 luci-app-opkg: update Simplified Chinese translation
  applications/luci-app-opkg/po/zh-cn/opkg.po
Labels: translation

#3186 luci-app-statistics: update Simplified Chinese translation
  applications/luci-app-statistics/po/zh-cn/statistics.po
Labels: translation

#3187 luci-app-adblock: update Simplified Chinese translation
  applications/luci-app-adblock/po/zh-cn/adblock.po
Labels: translation

#3145 luci-mod-system: refine flash reset
  modules/luci-base/root/usr/share/rpcd/acl.d/luci-base.json
  modules/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js
Labels: fix

#3125 [RFC] luci-app-cifsd: add new package
  applications/luci-app-cifsd/Makefile
  applications/luci-app-cifsd/htdocs/luci-static/resources/view/cifsd.js
  applications/luci-app-cifsd/luasrc/controller/cifsd.lua
  applications/luci-app-cifsd/root/usr/share/rpcd/acl.d/luci-app-cifsd.json
Labels: RFC, feature

#3190 Update from Weblate
  applications/luci-app-ahcp/po/es/ahcp.po
  applications/luci-app-commands/po/de/commands.po
  applications/luci-app-commands/po/es/commands.po
  applications/luci-app-coovachilli/po/es/coovachilli.po
  applications/luci-app-firewall/po/de/firewall.po
  applications/luci-app-firewall/po/es/firewall.po
  applications/luci-app-fwknopd/po/es/fwknopd.po
  applications/luci-app-minidlna/po/es/minidlna.po
  applications/luci-app-ntpc/po/es/ntpc.po
  applications/luci-app-nut/po/es/nut.po
  applications/luci-app-olsr/po/de/olsr.po
  applications/luci-app-olsr/po/es/olsr.po
  applications/luci-app-openvpn/po/de/openvpn.po
  applications/luci-app-opkg/po/es/opkg.po
  applications/luci-app-opkg/po/pt-br/opkg.po
  applications/luci-app-p910nd/po/de/p910nd.po
  applications/luci-app-qos/po/de/qos.po
  applications/luci-app-qos/po/es/qos.po
  applications/luci-app-samba/po/es/samba.po
  applications/luci-app-samba4/po/es/samba4.po
  applications/luci-app-splash/po/de/splash.po
  applications/luci-app-splash/po/es/splash.po
  applications/luci-app-statistics/po/ca/statistics.po
  applications/luci-app-statistics/po/de/statistics.po
  applications/luci-app-statistics/po/es/statistics.po
  applications/luci-app-tinyproxy/po/de/tinyproxy.po
  applications/luci-app-transmission/po/de/transmission.po
  applications/luci-app-uhttpd/po/de/uhttpd.po
  applications/luci-app-uhttpd/po/es/uhttpd.po
  applications/luci-app-upnp/po/de/upnp.po
  applications/luci-app-upnp/po/es/upnp.po
  applications/luci-app-wol/po/de/wol.po
  modules/luci-base/po/ca/base.po
  modules/luci-base/po/de/base.po
  modules/luci-base/po/es/base.po
Labels: translation

#3202 [RFC] luci-app-ttyd: add new package
  applications/luci-app-ttyd/Makefile
  applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/config.js
  applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/term.js
  applications/luci-app-ttyd/luasrc/controller/ttyd.lua
Labels: RFC, feature

#3210 luci-app-travelmate: sync with update 1.5.0
  applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
  applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
  applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm
  applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
Labels: depends on pr, feature

#3193 [19.07] luci-app-dcwapd: Add Dual Channel Wi-Fi AP Daemon Pages
  applications/luci-app-dcwapd/Makefile
  applications/luci-app-dcwapd/luasrc/controller/dcwapd.lua
  applications/luci-app-dcwapd/luasrc/model/cbi/dcwapd/dcwapd.lua
  applications/luci-app-dcwapd/po/es/dcwapd.po
  applications/luci-app-dcwapd/po/templates/dcwapd.pot
  applications/luci-app-dcwapd/root/etc/uci-defaults/60_luci-dcwapd
Labels: depends on pr, feature, release/19.07

#3178 luci-proto-qmi: add PDP type option
  protocols/luci-proto-qmi/htdocs/luci-static/resources/protocol/qmi.js
Labels: WIP, feature

#3239 luci-app-cifsd: fix read_only option incorrect default value
  applications/luci-app-cifsd/htdocs/luci-static/resources/view/cifsd.js
Labels: fix

#3224 [19.07] luci-app-vpnbypass: better service control buttons
  applications/luci-app-vpnbypass/Makefile
  applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/css.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status.htm
Labels: fix, release/19.07

#3225 [18.06] luci-app-vpnbypass: better service control buttons
  applications/luci-app-vpnbypass/Makefile
  applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/css.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status.htm
Labels: fix, release/18.06

#3223 luci-app-vpnbypass: better service control buttons
  applications/luci-app-vpnbypass/Makefile
  applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/css.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status.htm
Labels: fix

#3245 luci-app-vpnbypass: bugfix: call to action has no parent node
  applications/luci-app-vpnbypass/Makefile
  applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
Labels: fix

#3244 [19.07] luci-app-vpnbypass: bugfix: call to action has no parent node
  applications/luci-app-vpnbypass/Makefile
  applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
Labels: fix, release/19.07

#3246 [18.06] luci-app-vpnbypass: bugfix: call to action has no parent node
  applications/luci-app-vpnbypass/Makefile
  applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
Labels: fix, release/18.06
