Repository openwrt/luci, pull requests merged in 2019-11, with the labels that each got.

#2672 luci-mod-status: use available and cached memory for progress bars
  modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/20_memory.js
Labels: feature

#3240 [RFC] luci-app-shadowsocks-libev: port to client side
  applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/shadowsocks-libev.js
  applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/view/shadowsocks-libev/instances.js
  applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/view/shadowsocks-libev/rules.js
  applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/view/shadowsocks-libev/servers.js
  applications/luci-app-shadowsocks-libev/luasrc/controller/shadowsocks-libev.lua
  applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/instance-details.lua
  applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/instances.lua
  applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/rules.lua
  applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/servers.lua
  applications/luci-app-shadowsocks-libev/luasrc/model/shadowsocks-libev.lua
  applications/luci-app-shadowsocks-libev/luasrc/view/shadowsocks-libev/add_instance.htm
  applications/luci-app-shadowsocks-libev/root/etc/uci-defaults/40_luci-shadowsocks-libev
  applications/luci-app-shadowsocks-libev/root/usr/share/rpcd/acl.d/luci-app-shadowsocks-libev.json
Labels: RFC, WIP

#3267 luci-app-ddns: convert to client side implementation
  applications/luci-app-ddns/Makefile
  applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
  applications/luci-app-ddns/htdocs/luci-static/resources/view/status/include/70_ddns.js
  applications/luci-app-ddns/luasrc/controller/ddns.lua
  applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
  applications/luci-app-ddns/luasrc/model/cbi/ddns/global.lua
  applications/luci-app-ddns/luasrc/model/cbi/ddns/hints.lua
  applications/luci-app-ddns/luasrc/model/cbi/ddns/overview.lua
  applications/luci-app-ddns/luasrc/tools/ddns.lua
  applications/luci-app-ddns/luasrc/view/admin_status/index/ddns.htm
  applications/luci-app-ddns/luasrc/view/ddns/detail_logview.htm
  applications/luci-app-ddns/luasrc/view/ddns/detail_lvalue.htm
  applications/luci-app-ddns/luasrc/view/ddns/detail_value.htm
  applications/luci-app-ddns/luasrc/view/ddns/global_value.htm
  applications/luci-app-ddns/luasrc/view/ddns/overview_doubleline.htm
  applications/luci-app-ddns/luasrc/view/ddns/overview_enabled.htm
  applications/luci-app-ddns/luasrc/view/ddns/overview_startstop.htm
  applications/luci-app-ddns/luasrc/view/ddns/overview_status.htm
  applications/luci-app-ddns/luasrc/view/ddns/system_status.htm
  applications/luci-app-ddns/po/bg/ddns.po
  applications/luci-app-ddns/po/ca/ddns.po
  applications/luci-app-ddns/po/cs/ddns.po
  applications/luci-app-ddns/po/de/ddns.po
  applications/luci-app-ddns/po/el/ddns.po
  applications/luci-app-ddns/po/en/ddns.po
  applications/luci-app-ddns/po/es/ddns.po
  applications/luci-app-ddns/po/fr/ddns.po
  applications/luci-app-ddns/po/he/ddns.po
  applications/luci-app-ddns/po/hi/ddns.po
  applications/luci-app-ddns/po/hu/ddns.po
  applications/luci-app-ddns/po/it/ddns.po
  applications/luci-app-ddns/po/ja/ddns.po
  applications/luci-app-ddns/po/ko/ddns.po
  applications/luci-app-ddns/po/ms/ddns.po
  applications/luci-app-ddns/po/no/ddns.po
  applications/luci-app-ddns/po/pl/ddns.po
  applications/luci-app-ddns/po/pt-br/ddns.po
  applications/luci-app-ddns/po/pt/ddns.po
  applications/luci-app-ddns/po/ro/ddns.po
  applications/luci-app-ddns/po/ru/ddns.po
  applications/luci-app-ddns/po/sk/ddns.po
  applications/luci-app-ddns/po/sv/ddns.po
  applications/luci-app-ddns/po/templates/ddns.pot
  applications/luci-app-ddns/po/tr/ddns.po
  applications/luci-app-ddns/po/uk/ddns.po
  applications/luci-app-ddns/po/vi/ddns.po
  applications/luci-app-ddns/po/zh-cn/ddns.po
  applications/luci-app-ddns/po/zh-tw/ddns.po
  applications/luci-app-ddns/root/usr/libexec/rpcd/luci.ddns
  applications/luci-app-ddns/root/usr/share/rpcd/acl.d/luci-app-ddns.json
Labels: WIP, feature

#3310 luci-app-statistics: update misleading load view
  applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/load.lua
Labels: feature

#3258 luci-app-shadowsocks-libev: add server links import feature
  applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/shadowsocks-libev.js
  applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/view/shadowsocks-libev/servers.js
Labels: feature

#3291 luci-app-nextdns: add luci integration for nextdns package
  applications/luci-app-nextdns/Makefile
  applications/luci-app-nextdns/luasrc/controller/nextdns.lua
  applications/luci-app-nextdns/luasrc/model/cbi/overview.lua
  applications/luci-app-nextdns/luasrc/view/nextdns/logread.htm
  applications/luci-app-nextdns/po/templates/nextdns.pot
  applications/luci-app-nextdns/root/etc/uci-defaults/60_luci-nextdns
Labels: depends on pr, feature

#3322 luci-app-nextdns: add luci integration for nextdns package
  applications/luci-app-nextdns/Makefile
  applications/luci-app-nextdns/luasrc/controller/nextdns.lua
  applications/luci-app-nextdns/luasrc/model/cbi/overview.lua
  applications/luci-app-nextdns/luasrc/view/nextdns/logread.htm
  applications/luci-app-nextdns/po/templates/nextdns.pot
  applications/luci-app-nextdns/root/etc/uci-defaults/60_luci-nextdns
Labels: feature

#3323 luci-app-ddns: use the correct widget Select
  applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
Labels: fix

#3298 luci-app-mwan3: add new httping_ssl option
  applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
Labels: depends on pr, feature

#3330 luci-app-vpnbypass: use VPN node by default
  applications/luci-app-vpnbypass/Makefile
  applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
  applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm
Labels: feature, release/19.07
