Repository openwrt/luci, pull requests merged in 2019-09, with the labels that each got.

#3042 luci-base: hosts.js: Update chinese translations
  modules/luci-base/po/zh-cn/base.po
Labels: Translation

#1735 luci-app-olsr: handle empty result for non-status tables
  applications/luci-app-olsr/luasrc/controller/olsr.lua
Labels: fix, waiting for maintainer

#3083 luci-app-travelmate: add support for optional args in auto-login script
  applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
  applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
Labels: feature, waiting for maintainer

#2357 luci-mod-network: add master option
  modules/luci-base/po/ca/base.po
  modules/luci-base/po/cs/base.po
  modules/luci-base/po/de/base.po
  modules/luci-base/po/el/base.po
  modules/luci-base/po/en/base.po
  modules/luci-base/po/es/base.po
  modules/luci-base/po/fr/base.po
  modules/luci-base/po/he/base.po
  modules/luci-base/po/hu/base.po
  modules/luci-base/po/it/base.po
  modules/luci-base/po/ja/base.po
  modules/luci-base/po/ko/base.po
  modules/luci-base/po/ms/base.po
  modules/luci-base/po/no/base.po
  modules/luci-base/po/pl/base.po
  modules/luci-base/po/pt-br/base.po
  modules/luci-base/po/pt/base.po
  modules/luci-base/po/ro/base.po
  modules/luci-base/po/ru/base.po
  modules/luci-base/po/sk/base.po
  modules/luci-base/po/sv/base.po
  modules/luci-base/po/templates/base.pot
  modules/luci-base/po/tr/base.po
  modules/luci-base/po/uk/base.po
  modules/luci-base/po/vi/base.po
  modules/luci-base/po/zh-cn/base.po
  modules/luci-base/po/zh-tw/base.po
  modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
Labels: feature

#2756 luci-mod-network: permit WPS push-button on WPA3
  modules/luci-base/po/ca/base.po
  modules/luci-base/po/cs/base.po
  modules/luci-base/po/de/base.po
  modules/luci-base/po/el/base.po
  modules/luci-base/po/en/base.po
  modules/luci-base/po/es/base.po
  modules/luci-base/po/fr/base.po
  modules/luci-base/po/he/base.po
  modules/luci-base/po/hu/base.po
  modules/luci-base/po/it/base.po
  modules/luci-base/po/ja/base.po
  modules/luci-base/po/ko/base.po
  modules/luci-base/po/ms/base.po
  modules/luci-base/po/no/base.po
  modules/luci-base/po/pl/base.po
  modules/luci-base/po/pt-br/base.po
  modules/luci-base/po/pt/base.po
  modules/luci-base/po/ro/base.po
  modules/luci-base/po/ru/base.po
  modules/luci-base/po/sk/base.po
  modules/luci-base/po/sv/base.po
  modules/luci-base/po/templates/base.pot
  modules/luci-base/po/tr/base.po
  modules/luci-base/po/uk/base.po
  modules/luci-base/po/vi/base.po
  modules/luci-base/po/zh-cn/base.po
  modules/luci-base/po/zh-tw/base.po
  modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
Labels: probably a bug
