Repository openwrt/luci, pull requests merged in 2020-01, with the labels that each got.

#3391 luci-mod-network: Add description field to VLANs (trivial)
  modules/luci-mod-network/htdocs/luci-static/resources/view/network/switch.js
Labels: feature

#3444 luci-mod-network: add certificate subj validation
  modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
Labels: depends on pr, feature

#3473 luci-app-upnp: convert to client side implementation
  applications/luci-app-upnp/htdocs/luci-static/resources/view/status/include/80_upnp.js
  applications/luci-app-upnp/htdocs/luci-static/resources/view/upnp/upnp.js
  applications/luci-app-upnp/luasrc/controller/upnp.lua
  applications/luci-app-upnp/luasrc/model/cbi/upnp/upnp.lua
  applications/luci-app-upnp/luasrc/view/admin_status/index/upnp.htm
  applications/luci-app-upnp/luasrc/view/upnp_status.htm
  applications/luci-app-upnp/root/usr/libexec/rpcd/luci.upnp
  applications/luci-app-upnp/root/usr/share/rpcd/acl.d/luci-app-upnp.json
Labels: feature

#3514 luci-app-mosquitto: translations + option list fixes
  applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua
  applications/luci-app-mosquitto/po/templates/mosquitto.pot
Labels: fix

#3458 luci-app-vnstat2: add application
  applications/luci-app-vnstat2/Makefile
  applications/luci-app-vnstat2/htdocs/luci-static/resources/view/vnstat2/config.js
  applications/luci-app-vnstat2/luasrc/controller/vnstat2.lua
  applications/luci-app-vnstat2/luasrc/view/vnstat2/graphs.htm
  applications/luci-app-vnstat2/po/templates/vnstat2.pot
  applications/luci-app-vnstat2/root/usr/share/rpcd/acl.d/luci-app-vnstat2.json
Labels: feature

#3545 luci-app-ser2net: add app supporting ser2net
  applications/luci-app-ser2net/Makefile
  applications/luci-app-ser2net/htdocs/luci-static/resources/view/ser2net/leds.js
  applications/luci-app-ser2net/htdocs/luci-static/resources/view/ser2net/proxies.js
  applications/luci-app-ser2net/htdocs/luci-static/resources/view/ser2net/settings.js
  applications/luci-app-ser2net/luasrc/controller/ser2net.lua
  applications/luci-app-ser2net/root/usr/share/rpcd/acl.d/luci-app-ser2net.json
Labels: depends on pr, feature
