Repository openwrt/luci, pull requests merged in 2020-05, with the labels that each got.

#3956 luci-proto-bonding: add protohandler configuration for channel bonding
  protocols/luci-proto-bonding/Makefile
  protocols/luci-proto-bonding/htdocs/luci-static/resources/protocol/bonding.js
Labels: feature

#3978 luci-proto-openconnect: add usergroup option
  protocols/luci-proto-openconnect/htdocs/luci-static/resources/protocol/openconnect.js
Labels: depends on pr

#4038 luci-app-acme: Update acme.sh URL, add support for challenge & domain alises.
  applications/luci-app-acme/luasrc/model/cbi/acme.lua
Labels: depends on pr

#3953 luci-mod-admin-full: fixed ipv6 address display in the overview page of luci 18.06
  modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
Labels: release/18.06

#4047 luci-proto-wireguard: fix value validation
  protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js
Labels: fix

#4048 build/i18n-merge-master: ignore apps deleted in master
  build/i18n-merge-master.pl
Labels: release/19.07

#4104 [18.06] luci-app-ddns: fix huge typo in luasrc/tools/ddns.lua
  applications/luci-app-ddns/luasrc/tools/ddns.lua
Labels: release/18.06
