Repository openwrt/luci, pull requests merged in 2020-07, with the labels that each got.

#3413 luci-app-smartdns: add new package
  applications/luci-app-smartdns/Makefile
  applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
  applications/luci-app-smartdns/po/zh-cn/smartdns.po
  applications/luci-app-smartdns/root/usr/share/luci/menu.d/luci-app-smartdns.json
  applications/luci-app-smartdns/root/usr/share/rpcd/acl.d/luci-app-smartdns.json
Labels: WIP, depends on pr

#4249 luci-proto-modemmanager: add modem specific error messages
  protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
Labels: depends on pr

#4267 luci-app-statistics: add missing ValuesPercentage option
  applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/df.js
  applications/luci-app-statistics/root/etc/config/luci_statistics
  applications/luci-app-statistics/root/usr/share/luci/statistics/plugins/df.json
Labels: WIP, fix
