Repository openwrt/luci, pull requests merged in 2020-02, with the labels that each got.

#3173 [RFC] luci-app-frp: add new packages
  applications/luci-app-frpc/Makefile
  applications/luci-app-frpc/htdocs/luci-static/resources/view/frpc.js
  applications/luci-app-frpc/po/templates/frpc.pot
  applications/luci-app-frpc/root/usr/share/luci/menu.d/luci-app-frpc.json
  applications/luci-app-frpc/root/usr/share/rpcd/acl.d/luci-app-frpc.json
  applications/luci-app-frps/Makefile
  applications/luci-app-frps/htdocs/luci-static/resources/view/frps.js
  applications/luci-app-frps/po/templates/frps.pot
  applications/luci-app-frps/root/usr/share/luci/menu.d/luci-app-frps.json
  applications/luci-app-frps/root/usr/share/rpcd/acl.d/luci-app-frps.json
Labels: RFC, WIP, feature

#3621 [19.07] luci-app-samba4: add support for new UCI option
  applications/luci-app-samba4/htdocs/luci-static/resources/view/samba4.js
  applications/luci-app-samba4/po/bg/samba4.po
  applications/luci-app-samba4/po/ca/samba4.po
  applications/luci-app-samba4/po/cs/samba4.po
  applications/luci-app-samba4/po/de/samba4.po
  applications/luci-app-samba4/po/el/samba4.po
  applications/luci-app-samba4/po/en/samba4.po
  applications/luci-app-samba4/po/es/samba4.po
  applications/luci-app-samba4/po/fr/samba4.po
  applications/luci-app-samba4/po/he/samba4.po
  applications/luci-app-samba4/po/hi/samba4.po
  applications/luci-app-samba4/po/hu/samba4.po
  applications/luci-app-samba4/po/it/samba4.po
  applications/luci-app-samba4/po/ja/samba4.po
  applications/luci-app-samba4/po/ko/samba4.po
  applications/luci-app-samba4/po/mr/samba4.po
  applications/luci-app-samba4/po/ms/samba4.po
  applications/luci-app-samba4/po/nb_NO/samba4.po
  applications/luci-app-samba4/po/pl/samba4.po
  applications/luci-app-samba4/po/pt/samba4.po
  applications/luci-app-samba4/po/pt_BR/samba4.po
  applications/luci-app-samba4/po/ro/samba4.po
  applications/luci-app-samba4/po/ru/samba4.po
  applications/luci-app-samba4/po/sk/samba4.po
  applications/luci-app-samba4/po/sv/samba4.po
  applications/luci-app-samba4/po/templates/samba4.pot
  applications/luci-app-samba4/po/tr/samba4.po
  applications/luci-app-samba4/po/uk/samba4.po
  applications/luci-app-samba4/po/vi/samba4.po
  applications/luci-app-samba4/po/zh_Hans/samba4.po
  applications/luci-app-samba4/po/zh_Hant/samba4.po
Labels: release/19.07

#3619 luci-app-samba4: add support for new UCI option
  applications/luci-app-samba4/htdocs/luci-static/resources/view/samba4.js
  applications/luci-app-samba4/po/bg/samba4.po
  applications/luci-app-samba4/po/ca/samba4.po
  applications/luci-app-samba4/po/cs/samba4.po
  applications/luci-app-samba4/po/de/samba4.po
  applications/luci-app-samba4/po/el/samba4.po
  applications/luci-app-samba4/po/en/samba4.po
  applications/luci-app-samba4/po/es/samba4.po
  applications/luci-app-samba4/po/fr/samba4.po
  applications/luci-app-samba4/po/he/samba4.po
  applications/luci-app-samba4/po/hi/samba4.po
  applications/luci-app-samba4/po/hu/samba4.po
  applications/luci-app-samba4/po/it/samba4.po
  applications/luci-app-samba4/po/ja/samba4.po
  applications/luci-app-samba4/po/ko/samba4.po
  applications/luci-app-samba4/po/mr/samba4.po
  applications/luci-app-samba4/po/ms/samba4.po
  applications/luci-app-samba4/po/nb_NO/samba4.po
  applications/luci-app-samba4/po/pl/samba4.po
  applications/luci-app-samba4/po/pt/samba4.po
  applications/luci-app-samba4/po/pt_BR/samba4.po
  applications/luci-app-samba4/po/ro/samba4.po
  applications/luci-app-samba4/po/ru/samba4.po
  applications/luci-app-samba4/po/sk/samba4.po
  applications/luci-app-samba4/po/sv/samba4.po
  applications/luci-app-samba4/po/templates/samba4.pot
  applications/luci-app-samba4/po/tr/samba4.po
  applications/luci-app-samba4/po/uk/samba4.po
  applications/luci-app-samba4/po/vi/samba4.po
  applications/luci-app-samba4/po/zh_Hans/samba4.po
  applications/luci-app-samba4/po/zh_Hant/samba4.po
Labels: help wanted

#3622 [19.07] luci-app-ksmbd: support new UCI option, update for 3.2.1 version
  applications/luci-app-ksmbd/Makefile
  applications/luci-app-ksmbd/htdocs/luci-static/resources/view/ksmbd.js
  applications/luci-app-ksmbd/po/bg/ksmbd.po
  applications/luci-app-ksmbd/po/ca/ksmbd.po
  applications/luci-app-ksmbd/po/cs/ksmbd.po
  applications/luci-app-ksmbd/po/de/ksmbd.po
  applications/luci-app-ksmbd/po/el/ksmbd.po
  applications/luci-app-ksmbd/po/en/ksmbd.po
  applications/luci-app-ksmbd/po/es/ksmbd.po
  applications/luci-app-ksmbd/po/fr/ksmbd.po
  applications/luci-app-ksmbd/po/he/ksmbd.po
  applications/luci-app-ksmbd/po/hi/ksmbd.po
  applications/luci-app-ksmbd/po/hu/ksmbd.po
  applications/luci-app-ksmbd/po/it/ksmbd.po
  applications/luci-app-ksmbd/po/ko/ksmbd.po
  applications/luci-app-ksmbd/po/mr/ksmbd.po
  applications/luci-app-ksmbd/po/ms/ksmbd.po
  applications/luci-app-ksmbd/po/nb_NO/ksmbd.po
  applications/luci-app-ksmbd/po/pl/ksmbd.po
  applications/luci-app-ksmbd/po/pt/ksmbd.po
  applications/luci-app-ksmbd/po/pt_BR/ksmbd.po
  applications/luci-app-ksmbd/po/ro/ksmbd.po
  applications/luci-app-ksmbd/po/ru/ksmbd.po
  applications/luci-app-ksmbd/po/sk/ksmbd.po
  applications/luci-app-ksmbd/po/sv/ksmbd.po
  applications/luci-app-ksmbd/po/templates/ksmbd.pot
  applications/luci-app-ksmbd/po/tr/ksmbd.po
  applications/luci-app-ksmbd/po/uk/ksmbd.po
  applications/luci-app-ksmbd/po/vi/ksmbd.po
  applications/luci-app-ksmbd/po/zh_Hans/ksmbd.po
  applications/luci-app-ksmbd/po/zh_Hant/ksmbd.po
  applications/luci-app-ksmbd/root/usr/share/rpcd/acl.d/luci-app-ksmbd.json
Labels: release/19.07

#3639 luci-mod-system: add led plugin infrastructure
  applications/luci-app-ledtrig-rssi/Makefile
  applications/luci-app-ledtrig-rssi/htdocs/luci-static/resources/view/system/led-trigger/rssi.js
  applications/luci-app-ledtrig-switch/Makefile
  applications/luci-app-ledtrig-switch/htdocs/luci-static/resources/view/system/led-trigger/switch0.js
  applications/luci-app-ledtrig-switch/htdocs/luci-static/resources/view/system/led-trigger/switch1.js
  applications/luci-app-ledtrig-usbport/Makefile
  applications/luci-app-ledtrig-usbport/htdocs/luci-static/resources/view/system/led-trigger/usbport.js
  modules/luci-mod-system/Makefile
  modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/default-on.js
  modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/heartbeat.js
  modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/netdev.js
  modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/none.js
  modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/timer.js
  modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js
Labels: feature
