Repository openwrt/luci, pull requests merged in 2020-09, with the labels that each got.

#4351 luci-app-nft-qos: support mac address based speed limit
  applications/luci-app-nft-qos/luasrc/model/cbi/nft-qos/nft-qos.lua
Labels: depends on pr, feature

#4374 protocols: rename type to maptype for map
  protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/map.js
Labels: fix

#4402 [19.07] luci-app-opkg: flush menu cache after opkg actions
  applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
Labels: fix, release/19.07

#4411 luci-app-ttyd: rename menu entry to terminal
  applications/luci-app-ttyd/root/usr/share/luci/menu.d/luci-app-ttyd.json
Labels: fix

#4185 luci-mod-dashboard: initial checkin
  modules/luci-mod-dashboard/Makefile
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/css/custom.css
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/icons/devices.svg
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/icons/internet.svg
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/icons/not-internet.svg
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/icons/router.svg
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/icons/wireless.svg
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/10_router.js
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/20_lan.js
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/30_wifi.js
  modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/index.js
  modules/luci-mod-dashboard/root/usr/share/luci/menu.d/luci-mod-dashboard.json
  modules/luci-mod-dashboard/root/usr/share/rpcd/acl.d/luci-mod-dashboard.json
Labels: New package

#4408 luci-app-statistics: add noavg option
  applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool.js
Labels: feature

#3265 luci-mod-network: add address parameter in DHCP for dnsmasq
  modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
Labels: feature
