Repository openwrt/luci, pull requests merged in 2021-03, with the labels that each got.

#4658 luci-app-watchcat: add support for new features + JS refactor
  applications/luci-app-watchcat/Makefile
  applications/luci-app-watchcat/htdocs/luci-static/resources/view/watchcat.js
  applications/luci-app-watchcat/luasrc/model/cbi/watchcat/watchcat.lua
  applications/luci-app-watchcat/po/ar/watchcat.po
  applications/luci-app-watchcat/po/bg/watchcat.po
  applications/luci-app-watchcat/po/bn_BD/watchcat.po
  applications/luci-app-watchcat/po/ca/watchcat.po
  applications/luci-app-watchcat/po/cs/watchcat.po
  applications/luci-app-watchcat/po/de/watchcat.po
  applications/luci-app-watchcat/po/el/watchcat.po
  applications/luci-app-watchcat/po/en/watchcat.po
  applications/luci-app-watchcat/po/es/watchcat.po
  applications/luci-app-watchcat/po/fi/watchcat.po
  applications/luci-app-watchcat/po/fr/watchcat.po
  applications/luci-app-watchcat/po/he/watchcat.po
  applications/luci-app-watchcat/po/hi/watchcat.po
  applications/luci-app-watchcat/po/hu/watchcat.po
  applications/luci-app-watchcat/po/it/watchcat.po
  applications/luci-app-watchcat/po/ja/watchcat.po
  applications/luci-app-watchcat/po/ko/watchcat.po
  applications/luci-app-watchcat/po/mr/watchcat.po
  applications/luci-app-watchcat/po/ms/watchcat.po
  applications/luci-app-watchcat/po/nb_NO/watchcat.po
  applications/luci-app-watchcat/po/pl/watchcat.po
  applications/luci-app-watchcat/po/pt/watchcat.po
  applications/luci-app-watchcat/po/pt_BR/watchcat.po
  applications/luci-app-watchcat/po/ro/watchcat.po
  applications/luci-app-watchcat/po/ru/watchcat.po
  applications/luci-app-watchcat/po/sk/watchcat.po
  applications/luci-app-watchcat/po/sv/watchcat.po
  applications/luci-app-watchcat/po/templates/watchcat.pot
  applications/luci-app-watchcat/po/tr/watchcat.po
  applications/luci-app-watchcat/po/uk/watchcat.po
  applications/luci-app-watchcat/po/vi/watchcat.po
  applications/luci-app-watchcat/po/zh_Hans/watchcat.po
  applications/luci-app-watchcat/po/zh_Hant/watchcat.po
  applications/luci-app-watchcat/root/usr/share/luci/menu.d/luci-app-watchcat.json
  applications/luci-app-watchcat/root/usr/share/rpcd/acl.d/luci-app-watchcat.json
Labels: depends on pr

#4931 [21.02] luci-app-attendedsysupgrade: sync with master branch
  applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/configuration.js
  applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
  applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
  applications/luci-app-attendedsysupgrade/root/etc/uci-defaults/40_luci-attendedsysupgrade
  applications/luci-app-attendedsysupgrade/root/usr/share/luci/menu.d/luci-app-attendedsysupgrade.json
  applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/attendedsysupgrade.json
  applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/luci-app-attendedsysupgrade.json
  applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
Labels: release/21.02

#4932 luci-app-watchcat: add support for new features and convert to JavaScript
  applications/luci-app-watchcat/Makefile
  applications/luci-app-watchcat/htdocs/luci-static/resources/view/watchcat.js
  applications/luci-app-watchcat/luasrc/model/cbi/watchcat/watchcat.lua
  applications/luci-app-watchcat/root/usr/share/luci/menu.d/luci-app-watchcat.json
  applications/luci-app-watchcat/root/usr/share/rpcd/acl.d/luci-app-watchcat.json
Labels: depends on pr, release/21.02
