Repository openwrt/luci, pull requests merged in 2023-12, with the labels that each got.

#4328 luci-proto-modemmanger: add missing proto options
  protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
Labels: feature

#6574 Fix ATM HEC label on stats.js
  modules/luci-mod-dsl/htdocs/luci-static/resources/view/status/dsl/stats.js
  modules/luci-mod-dsl/po/cs/dsl.po
  modules/luci-mod-dsl/po/da/dsl.po
  modules/luci-mod-dsl/po/de/dsl.po
  modules/luci-mod-dsl/po/es/dsl.po
  modules/luci-mod-dsl/po/fr/dsl.po
  modules/luci-mod-dsl/po/it/dsl.po
  modules/luci-mod-dsl/po/lt/dsl.po
  modules/luci-mod-dsl/po/nb_NO/dsl.po
  modules/luci-mod-dsl/po/pl/dsl.po
  modules/luci-mod-dsl/po/pt/dsl.po
  modules/luci-mod-dsl/po/pt_BR/dsl.po
  modules/luci-mod-dsl/po/ro/dsl.po
  modules/luci-mod-dsl/po/ru/dsl.po
  modules/luci-mod-dsl/po/sv/dsl.po
  modules/luci-mod-dsl/po/templates/dsl.pot
  modules/luci-mod-dsl/po/tr/dsl.po
  modules/luci-mod-dsl/po/uk/dsl.po
  modules/luci-mod-dsl/po/vi/dsl.po
  modules/luci-mod-dsl/po/zh_Hans/dsl.po
  modules/luci-mod-dsl/po/zh_Hant/dsl.po
Labels: fix

#6623 [23.05] backport "luci-app-attendedsysupgrade: add x86 efi/bios case"
  applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
Labels: fix, Work needed

#6746 luci-app-vnstat2: fix configuration page when database is empty
  applications/luci-app-vnstat2/htdocs/luci-static/resources/view/vnstat2/config.js
Labels: fix, release/22.03, release/23.05

#6743 [23.05] luci-app-adblock-fast: update to 1.1.0-1
  applications/luci-app-adblock-fast/Makefile
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
  applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
  applications/luci-app-adblock-fast/root/usr/share/rpcd/acl.d/luci-app-adblock-fast.json
Labels: depends on other pr, release/23.05

#6748 luci-app-adblock-fast: sync with principal package
  applications/luci-app-adblock-fast/Makefile
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
  applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
Labels: depends on other pr

#6749 [23.05] luci-app-adblock-fast: sync with principal package
  applications/luci-app-adblock-fast/Makefile
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
  applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
Labels: depends on other pr, release/23.05

#6757 [23.05] luci-app-adblock-fast: bugfix: L.uci.load
  applications/luci-app-adblock-fast/Makefile
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
Labels: release/23.05

#6760 [23.05] luci-app-adblock-fast: improve dnsmasq/smartdns instances selection
  applications/luci-app-adblock-fast/Makefile
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
Labels: release/23.05

#6762 [22.03] luci-app-https-dns-proxy: update to 2023-10-25-5
  applications/luci-app-https-dns-proxy/Makefile
  applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
  applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
  applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
  applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy
Labels: release/22.03

#6763 [23.05] luci-app-https-dns-proxy: update to 2023-10-25-5
  applications/luci-app-https-dns-proxy/Makefile
  applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
  applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
  applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
  applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy
Labels: release/23.05

#6768 [23.05] luci-app-adblock-fast: update to 1.1.1-1
  applications/luci-app-adblock-fast/Makefile
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
  applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
  applications/luci-app-adblock-fast/root/usr/share/rpcd/acl.d/luci-app-adblock-fast.json
Labels: release/23.05

#6769 luci-app-adblock-fast: bugfix: remove instance selection...
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
Labels: fix

#6770 [23.05] luci-app-adblock-fast: bugfix: remove instance selection
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
Labels: fix, release/23.05

#6700 luci-app-strongswan-swanctl: initial commit
  applications/luci-app-strongswan-swanctl/Makefile
  applications/luci-app-strongswan-swanctl/htdocs/luci-static/resources/strongswan_algorithms.js
  applications/luci-app-strongswan-swanctl/htdocs/luci-static/resources/view/strongswan-swanctl/status.js
  applications/luci-app-strongswan-swanctl/htdocs/luci-static/resources/view/strongswan-swanctl/swanctl.js
  applications/luci-app-strongswan-swanctl/root/usr/share/luci/menu.d/luci-app-strongswan-swanctl.json
  applications/luci-app-strongswan-swanctl/root/usr/share/rpcd/acl.d/luci-app-strongswan-swanctl.json
Labels: depends on other pr, feature

#6566 luci-app-strongswan-ipsec: add package
  applications/luci-app-strongswan-ipsec/Makefile
  applications/luci-app-strongswan-ipsec/htdocs/luci-static/resources/view/ipsec.js
  applications/luci-app-strongswan-ipsec/root/etc/config/ipsec
  applications/luci-app-strongswan-ipsec/root/usr/share/luci/menu.d/luci-app-strongswan-ipsec.json
  applications/luci-app-strongswan-ipsec/root/usr/share/rpcd/acl.d/luci-app-strongswan-ipsec.json
Labels: feature, WIP, Work needed

#6724 luci-mod-status: fix ACL for channel analysis
  modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json
Labels: fix

#6723 luci-mod-status: highlight primary 20 MHz channel
  modules/luci-mod-status/htdocs/luci-static/resources/svg/channel_analysis.svg
  modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js
Labels: feature, fix

#6737 luci-mod-network: DHCP tab IPsets ( add NFTsets properties )
  modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
Labels: WIP, fix, Work needed
