Repository openwrt/luci, pull requests merged in 2024-02, with the labels that each got.

#6889 [23.05] luci-app-adblock-fast: bugfix: prevent runtime errors on empty strings
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
Labels: release/23.05

#6877 luci-app-openvpn: add OpenVPN option disable-dco
  applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
Labels: feature, depends on PR in other repo

#6906 [23.05] luci-app-opkg: show disk space consistent with overview
  applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
Labels: release/23.05

#6911 [23.05] luci-app-adblock-fast: bugfix: dnsmasq_instance & smartdns_instance p…
  applications/luci-app-adblock-fast/Makefile
  applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
  applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
Labels: release/23.05

#6923 [22.03] luci-app-https-dns-proxy: bugfix: dnsmasq_instance parsing
  applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
  applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
Labels: release/22.03

#6924 [23.05] luci-app-https-dns-proxy: bugfix: dnsmasq_instance parsing
  applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
  applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
Labels: release/23.05
