Repository openwrt/luci, pull requests merged in 2024-04, with the labels that each got.

#7045 [23.05] luci-app-https-dns-proxy: bugfix: AdGuard servers URLs
  applications/luci-app-https-dns-proxy/Makefile
  applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/com.adguard.dns.json
Labels: release/23.05

#6553 Add File Manager / File Browser based on form.FileUpload
  applications/luci-app-filebrowser/Makefile
  applications/luci-app-filebrowser/htdocs/luci-static/resources/view/system/filebrowser.js
  applications/luci-app-filebrowser/po/templates/filebrowser.pot
  applications/luci-app-filebrowser/root/usr/share/luci/menu.d/luci-app-filebrowser.json
  applications/luci-app-filebrowser/root/usr/share/rpcd/acl.d/luci-app-filebrowser.json
  modules/luci-base/htdocs/luci-static/resources/form.js
  modules/luci-base/htdocs/luci-static/resources/ui.js
Labels: feature, fix, Needs testing

#7053 [23.05] luci-app-https-dns-proxy: bugfix: status/overview page include
  applications/luci-app-https-dns-proxy/Makefile
  applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
  applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
Labels: release/23.05

#7054 [22.03] luci-app-https-dns-proxy: 3 cherry-picks to bring up to date with bugfixes.
  applications/luci-app-https-dns-proxy/Makefile
  applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
  applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
  applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy
  applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/com.adguard.dns.json
Labels: release/22.03

#7057 luci-app-pbr: sync with principal package
  applications/luci-app-pbr/Makefile
  applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js
  applications/luci-app-pbr/po/templates/pbr.pot
Labels: depends on PR in other repo

#7061 luci-app-pbr: sync with principal package
  applications/luci-app-pbr/Makefile
Labels: depends on other pr

#6456 luci-app-lldpd: Create based on TanoWrt's app
  applications/luci-app-lldpd/Makefile
  applications/luci-app-lldpd/htdocs/luci-static/resources/lldpd.js
  applications/luci-app-lldpd/htdocs/luci-static/resources/lldpd/details_hide.svg
  applications/luci-app-lldpd/htdocs/luci-static/resources/lldpd/details_show.svg
  applications/luci-app-lldpd/htdocs/luci-static/resources/lldpd/lldpd.css
  applications/luci-app-lldpd/htdocs/luci-static/resources/view/lldpd/config.js
  applications/luci-app-lldpd/htdocs/luci-static/resources/view/lldpd/status.js
  applications/luci-app-lldpd/po/ru/lldpd.po
  applications/luci-app-lldpd/po/templates/lldpd.pot
  applications/luci-app-lldpd/root/etc/uci-defaults/40_luci-lldpd
  applications/luci-app-lldpd/root/usr/share/luci/menu.d/luci-app-lldpd.json
  applications/luci-app-lldpd/root/usr/share/rpcd/acl.d/luci-app-lldpd.json
  applications/luci-app-lldpd/root/usr/share/rpcd/ucode/lldpd
Labels: feature, depends on PR in other repo
