Repository openwrt/luci, pull requests merged in 2024-03, with the labels that each got.

#6347 luci-base: ui.js: avoid polling in a tight loop on confirm/rollback
  modules/luci-base/htdocs/luci-static/resources/ui.js
Labels: fix

#6999 luci-app-pbr: update to 1.1.4-5
  applications/luci-app-pbr/Makefile
  applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js
  applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js
  applications/luci-app-pbr/htdocs/luci-static/resources/view/status/include/72_pbr.js
  applications/luci-app-pbr/po/templates/pbr.pot
  applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr
  applications/luci-app-pbr/root/usr/share/rpcd/acl.d/luci-app-pbr.json
Labels: depends on other pr

#7018 [23.05] luci-proto-nebula: prepare migration to APK
  protocols/luci-proto-nebula/Makefile
Labels: release/23.05

#7015 [23.05] luci-app-advanced-reboot: prepare migration to APK
  applications/luci-app-advanced-reboot/Makefile
  applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/dlink-fgs1210-28.json
  applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea8100v1.json
Labels: release/23.05

#7016 [23.05] luci-app-https-dns-proxy: prepare migration to APK
  applications/luci-app-https-dns-proxy/Makefile
  applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy
Labels: release/23.05
